# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.cache/wt} [current_project]
set_property parent.project_path {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo {f:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/AND_p.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/NOT_p.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/NAND_p.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/NAND_p3.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/Mux2_1.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/OR_p.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/XOR_p.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/FullAdder1.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/mux4_1_1.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/mux8_1.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/ALU1b.vhd}
  {F:/Facultate/An III/sem2/SSC/Microcontroler8051/Microcontroler8051.srcs/sources_1/new/ALU8bit.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top ALU8bit -part xc7a200tfbg676-2


write_checkpoint -force -noxdef ALU8bit.dcp

catch { report_utilization -file ALU8bit_utilization_synth.rpt -pb ALU8bit_utilization_synth.pb }
